"""Mudanças

Revision ID: 1955cf514668
Revises: 29c35990ee88
Create Date: 2022-03-24 08:47:47.369795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1955cf514668'
down_revision = '29c35990ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nucleos', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('disco', sa.BigInteger(), nullable=False),
    sa.Column('ram', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.add_column('vm', sa.Column('host_p', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vm', 'host', ['host_p'], ['nome'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm', type_='foreignkey')
    op.drop_column('vm', 'host_p')
    op.drop_table('host')
    # ### end Alembic commands ###
