"""Migrar

Revision ID: 43011e5bd31f
Revises: 1955cf514668
Create Date: 2022-04-01 08:21:55.710842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43011e5bd31f'
down_revision = '1955cf514668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('vm', sa.Column('mac', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'mac')
    op.drop_column('vm', 'ip')
    # ### end Alembic commands ###
