"""Migrar

Revision ID: 552de9bd95cd
Revises: 43011e5bd31f
Create Date: 2022-04-01 09:44:32.041714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552de9bd95cd'
down_revision = '43011e5bd31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('codigo_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo_id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo')
    # ### end Alembic commands ###
