"""Migrar

Revision ID: 835c2007c584
Revises: 552de9bd95cd
Create Date: 2022-04-01 09:45:59.341781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835c2007c584'
down_revision = '552de9bd95cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('grupo', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'vm', 'grupo', ['grupo'], ['codigo_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vm', type_='foreignkey')
    op.drop_column('vm', 'grupo')
    # ### end Alembic commands ###
