"""empty message

Revision ID: e4b159e18385
Revises: 
Create Date: 2022-03-17 09:06:45.406947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b159e18385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('ativo_dias', sa.Integer(), nullable=False))
    op.add_column('vm', sa.Column('ativo_horas', sa.Integer(), nullable=False))
    op.add_column('vm', sa.Column('total_ativo_dias', sa.Integer(), nullable=False))
    op.add_column('vm', sa.Column('total_ativo_horas', sa.Integer(), nullable=False))
    op.add_column('vm', sa.Column('desativada', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'desativada')
    op.drop_column('vm', 'total_ativo_horas')
    op.drop_column('vm', 'total_ativo_dias')
    op.drop_column('vm', 'ativo_horas')
    op.drop_column('vm', 'ativo_dias')
    # ### end Alembic commands ###
